FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY sentinel-frontend/package*.json ./
RUN npm install

COPY sentinel-frontend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]